export enum AnalysisStatus {
    SCRAPED = 'SCRAPED',
    SCRAPING = 'SCRAPING',
    SCRAPING_FAILED = 'SCRAPING_FAILED',
    AI_PROCESSING = 'AI_PROCESSING',
    COMPLETED = 'COMPLETED',
    AI_FAILED = 'AI_FAILED',
    INSUFFICIENT_DATA = 'INSUFFICIENT_DATA',
}
